// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: packages/contracts/runtimev1/runtime.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateInstanceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstanceId     string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`               // KSUID
	ImageUrl       string                 `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`                     // object storage URL for base image
	InstanceTypeId string                 `protobuf:"bytes,3,opt,name=instance_type_id,json=instanceTypeId,proto3" json:"instance_type_id,omitempty"` // e.g. c1.small
	CpuCores       int32                  `protobuf:"varint,4,opt,name=cpu_cores,json=cpuCores,proto3" json:"cpu_cores,omitempty"`
	MemoryMb       int32                  `protobuf:"varint,5,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	DiskGb         int32                  `protobuf:"varint,6,opt,name=disk_gb,json=diskGb,proto3" json:"disk_gb,omitempty"`
	RootfsPath     string                 `protobuf:"bytes,7,opt,name=rootfs_path,json=rootfsPath,proto3" json:"rootfs_path,omitempty"` // NFS path for qcow2 CoW overlay
	Network        *NetworkConfig         `protobuf:"bytes,8,opt,name=network,proto3" json:"network,omitempty"`
	SshPublicKey   string                 `protobuf:"bytes,9,opt,name=ssh_public_key,json=sshPublicKey,proto3" json:"ssh_public_key,omitempty"` // injected via metadata service
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateInstanceRequest) Reset() {
	*x = CreateInstanceRequest{}
	mi := &file_packages_contracts_runtimev1_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstanceRequest) ProtoMessage() {}

func (x *CreateInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_runtimev1_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstanceRequest.ProtoReflect.Descriptor instead.
func (*CreateInstanceRequest) Descriptor() ([]byte, []int) {
	return file_packages_contracts_runtimev1_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *CreateInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CreateInstanceRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *CreateInstanceRequest) GetInstanceTypeId() string {
	if x != nil {
		return x.InstanceTypeId
	}
	return ""
}

func (x *CreateInstanceRequest) GetCpuCores() int32 {
	if x != nil {
		return x.CpuCores
	}
	return 0
}

func (x *CreateInstanceRequest) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *CreateInstanceRequest) GetDiskGb() int32 {
	if x != nil {
		return x.DiskGb
	}
	return 0
}

func (x *CreateInstanceRequest) GetRootfsPath() string {
	if x != nil {
		return x.RootfsPath
	}
	return ""
}

func (x *CreateInstanceRequest) GetNetwork() *NetworkConfig {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *CreateInstanceRequest) GetSshPublicKey() string {
	if x != nil {
		return x.SshPublicKey
	}
	return ""
}

type CreateInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // "CREATED"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInstanceResponse) Reset() {
	*x = CreateInstanceResponse{}
	mi := &file_packages_contracts_runtimev1_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstanceResponse) ProtoMessage() {}

func (x *CreateInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_runtimev1_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstanceResponse.ProtoReflect.Descriptor instead.
func (*CreateInstanceResponse) Descriptor() ([]byte, []int) {
	return file_packages_contracts_runtimev1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *CreateInstanceResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CreateInstanceResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type StartInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartInstanceRequest) Reset() {
	*x = StartInstanceRequest{}
	mi := &file_packages_contracts_runtimev1_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartInstanceRequest) ProtoMessage() {}

func (x *StartInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_runtimev1_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartInstanceRequest.ProtoReflect.Descriptor instead.
func (*StartInstanceRequest) Descriptor() ([]byte, []int) {
	return file_packages_contracts_runtimev1_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *StartInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type StartInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // "RUNNING"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartInstanceResponse) Reset() {
	*x = StartInstanceResponse{}
	mi := &file_packages_contracts_runtimev1_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartInstanceResponse) ProtoMessage() {}

func (x *StartInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_runtimev1_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartInstanceResponse.ProtoReflect.Descriptor instead.
func (*StartInstanceResponse) Descriptor() ([]byte, []int) {
	return file_packages_contracts_runtimev1_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *StartInstanceResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StartInstanceResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type StopInstanceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstanceId     string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,2,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"` // ACPI grace period before force-kill. Default 90.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StopInstanceRequest) Reset() {
	*x = StopInstanceRequest{}
	mi := &file_packages_contracts_runtimev1_runtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopInstanceRequest) ProtoMessage() {}

func (x *StopInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_runtimev1_runtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopInstanceRequest.ProtoReflect.Descriptor instead.
func (*StopInstanceRequest) Descriptor() ([]byte, []int) {
	return file_packages_contracts_runtimev1_runtime_proto_rawDescGZIP(), []int{4}
}

func (x *StopInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StopInstanceRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type StopInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // "STOPPED"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopInstanceResponse) Reset() {
	*x = StopInstanceResponse{}
	mi := &file_packages_contracts_runtimev1_runtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopInstanceResponse) ProtoMessage() {}

func (x *StopInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_runtimev1_runtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopInstanceResponse.ProtoReflect.Descriptor instead.
func (*StopInstanceResponse) Descriptor() ([]byte, []int) {
	return file_packages_contracts_runtimev1_runtime_proto_rawDescGZIP(), []int{5}
}

func (x *StopInstanceResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StopInstanceResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type DeleteInstanceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstanceId     string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	DeleteRootDisk bool                   `protobuf:"varint,2,opt,name=delete_root_disk,json=deleteRootDisk,proto3" json:"delete_root_disk,omitempty"` // Phase 1: always true.
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteInstanceRequest) Reset() {
	*x = DeleteInstanceRequest{}
	mi := &file_packages_contracts_runtimev1_runtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInstanceRequest) ProtoMessage() {}

func (x *DeleteInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_runtimev1_runtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInstanceRequest.ProtoReflect.Descriptor instead.
func (*DeleteInstanceRequest) Descriptor() ([]byte, []int) {
	return file_packages_contracts_runtimev1_runtime_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *DeleteInstanceRequest) GetDeleteRootDisk() bool {
	if x != nil {
		return x.DeleteRootDisk
	}
	return false
}

type DeleteInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"` // "DELETED"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInstanceResponse) Reset() {
	*x = DeleteInstanceResponse{}
	mi := &file_packages_contracts_runtimev1_runtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInstanceResponse) ProtoMessage() {}

func (x *DeleteInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_runtimev1_runtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInstanceResponse.ProtoReflect.Descriptor instead.
func (*DeleteInstanceResponse) Descriptor() ([]byte, []int) {
	return file_packages_contracts_runtimev1_runtime_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteInstanceResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *DeleteInstanceResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type ListInstancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstancesRequest) Reset() {
	*x = ListInstancesRequest{}
	mi := &file_packages_contracts_runtimev1_runtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstancesRequest) ProtoMessage() {}

func (x *ListInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_runtimev1_runtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstancesRequest.ProtoReflect.Descriptor instead.
func (*ListInstancesRequest) Descriptor() ([]byte, []int) {
	return file_packages_contracts_runtimev1_runtime_proto_rawDescGZIP(), []int{8}
}

type ListInstancesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instances     []*InstanceStatus      `protobuf:"bytes,1,rep,name=instances,proto3" json:"instances,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstancesResponse) Reset() {
	*x = ListInstancesResponse{}
	mi := &file_packages_contracts_runtimev1_runtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstancesResponse) ProtoMessage() {}

func (x *ListInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_runtimev1_runtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstancesResponse.ProtoReflect.Descriptor instead.
func (*ListInstancesResponse) Descriptor() ([]byte, []int) {
	return file_packages_contracts_runtimev1_runtime_proto_rawDescGZIP(), []int{9}
}

func (x *ListInstancesResponse) GetInstances() []*InstanceStatus {
	if x != nil {
		return x.Instances
	}
	return nil
}

type InstanceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`                     // CREATED, RUNNING, STOPPED, DELETED
	HostPid       int32                  `protobuf:"varint,3,opt,name=host_pid,json=hostPid,proto3" json:"host_pid,omitempty"` // Firecracker process PID; 0 if not running
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceStatus) Reset() {
	*x = InstanceStatus{}
	mi := &file_packages_contracts_runtimev1_runtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceStatus) ProtoMessage() {}

func (x *InstanceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_runtimev1_runtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceStatus.ProtoReflect.Descriptor instead.
func (*InstanceStatus) Descriptor() ([]byte, []int) {
	return file_packages_contracts_runtimev1_runtime_proto_rawDescGZIP(), []int{10}
}

func (x *InstanceStatus) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *InstanceStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *InstanceStatus) GetHostPid() int32 {
	if x != nil {
		return x.HostPid
	}
	return 0
}

type NetworkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PrivateIp     string                 `protobuf:"bytes,1,opt,name=private_ip,json=privateIp,proto3" json:"private_ip,omitempty"` // assigned from ip_allocations pool
	PublicIp      string                 `protobuf:"bytes,2,opt,name=public_ip,json=publicIp,proto3" json:"public_ip,omitempty"`    // optional; empty if no public IP
	TapDevice     string                 `protobuf:"bytes,3,opt,name=tap_device,json=tapDevice,proto3" json:"tap_device,omitempty"` // TAP device name on host (e.g. tap0)
	MacAddress    string                 `protobuf:"bytes,4,opt,name=mac_address,json=macAddress,proto3" json:"mac_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_packages_contracts_runtimev1_runtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_packages_contracts_runtimev1_runtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_packages_contracts_runtimev1_runtime_proto_rawDescGZIP(), []int{11}
}

func (x *NetworkConfig) GetPrivateIp() string {
	if x != nil {
		return x.PrivateIp
	}
	return ""
}

func (x *NetworkConfig) GetPublicIp() string {
	if x != nil {
		return x.PublicIp
	}
	return ""
}

func (x *NetworkConfig) GetTapDevice() string {
	if x != nil {
		return x.TapDevice
	}
	return ""
}

func (x *NetworkConfig) GetMacAddress() string {
	if x != nil {
		return x.MacAddress
	}
	return ""
}

var File_packages_contracts_runtimev1_runtime_proto protoreflect.FileDescriptor

const file_packages_contracts_runtimev1_runtime_proto_rawDesc = "" +
	"\n" +
	"*packages/contracts/runtimev1/runtime.proto\x12\truntimev1\"\xcd\x02\n" +
	"\x15CreateInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1b\n" +
	"\timage_url\x18\x02 \x01(\tR\bimageUrl\x12(\n" +
	"\x10instance_type_id\x18\x03 \x01(\tR\x0einstanceTypeId\x12\x1b\n" +
	"\tcpu_cores\x18\x04 \x01(\x05R\bcpuCores\x12\x1b\n" +
	"\tmemory_mb\x18\x05 \x01(\x05R\bmemoryMb\x12\x17\n" +
	"\adisk_gb\x18\x06 \x01(\x05R\x06diskGb\x12\x1f\n" +
	"\vrootfs_path\x18\a \x01(\tR\n" +
	"rootfsPath\x122\n" +
	"\anetwork\x18\b \x01(\v2\x18.runtimev1.NetworkConfigR\anetwork\x12$\n" +
	"\x0essh_public_key\x18\t \x01(\tR\fsshPublicKey\"O\n" +
	"\x16CreateInstanceResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"7\n" +
	"\x14StartInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"N\n" +
	"\x15StartInstanceResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"_\n" +
	"\x13StopInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12'\n" +
	"\x0ftimeout_seconds\x18\x02 \x01(\x05R\x0etimeoutSeconds\"M\n" +
	"\x14StopInstanceResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"b\n" +
	"\x15DeleteInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12(\n" +
	"\x10delete_root_disk\x18\x02 \x01(\bR\x0edeleteRootDisk\"O\n" +
	"\x16DeleteInstanceResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"\x16\n" +
	"\x14ListInstancesRequest\"P\n" +
	"\x15ListInstancesResponse\x127\n" +
	"\tinstances\x18\x01 \x03(\v2\x19.runtimev1.InstanceStatusR\tinstances\"b\n" +
	"\x0eInstanceStatus\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12\x19\n" +
	"\bhost_pid\x18\x03 \x01(\x05R\ahostPid\"\x8b\x01\n" +
	"\rNetworkConfig\x12\x1d\n" +
	"\n" +
	"private_ip\x18\x01 \x01(\tR\tprivateIp\x12\x1b\n" +
	"\tpublic_ip\x18\x02 \x01(\tR\bpublicIp\x12\x1d\n" +
	"\n" +
	"tap_device\x18\x03 \x01(\tR\ttapDevice\x12\x1f\n" +
	"\vmac_address\x18\x04 \x01(\tR\n" +
	"macAddress2\xb7\x03\n" +
	"\x0eRuntimeService\x12U\n" +
	"\x0eCreateInstance\x12 .runtimev1.CreateInstanceRequest\x1a!.runtimev1.CreateInstanceResponse\x12R\n" +
	"\rStartInstance\x12\x1f.runtimev1.StartInstanceRequest\x1a .runtimev1.StartInstanceResponse\x12O\n" +
	"\fStopInstance\x12\x1e.runtimev1.StopInstanceRequest\x1a\x1f.runtimev1.StopInstanceResponse\x12U\n" +
	"\x0eDeleteInstance\x12 .runtimev1.DeleteInstanceRequest\x1a!.runtimev1.DeleteInstanceResponse\x12R\n" +
	"\rListInstances\x12\x1f.runtimev1.ListInstancesRequest\x1a .runtimev1.ListInstancesResponseBKZIgithub.com/compute-platform/compute-platform/packages/contracts/runtimev1b\x06proto3"

var (
	file_packages_contracts_runtimev1_runtime_proto_rawDescOnce sync.Once
	file_packages_contracts_runtimev1_runtime_proto_rawDescData []byte
)

func file_packages_contracts_runtimev1_runtime_proto_rawDescGZIP() []byte {
	file_packages_contracts_runtimev1_runtime_proto_rawDescOnce.Do(func() {
		file_packages_contracts_runtimev1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packages_contracts_runtimev1_runtime_proto_rawDesc), len(file_packages_contracts_runtimev1_runtime_proto_rawDesc)))
	})
	return file_packages_contracts_runtimev1_runtime_proto_rawDescData
}

var file_packages_contracts_runtimev1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_packages_contracts_runtimev1_runtime_proto_goTypes = []any{
	(*CreateInstanceRequest)(nil),  // 0: runtimev1.CreateInstanceRequest
	(*CreateInstanceResponse)(nil), // 1: runtimev1.CreateInstanceResponse
	(*StartInstanceRequest)(nil),   // 2: runtimev1.StartInstanceRequest
	(*StartInstanceResponse)(nil),  // 3: runtimev1.StartInstanceResponse
	(*StopInstanceRequest)(nil),    // 4: runtimev1.StopInstanceRequest
	(*StopInstanceResponse)(nil),   // 5: runtimev1.StopInstanceResponse
	(*DeleteInstanceRequest)(nil),  // 6: runtimev1.DeleteInstanceRequest
	(*DeleteInstanceResponse)(nil), // 7: runtimev1.DeleteInstanceResponse
	(*ListInstancesRequest)(nil),   // 8: runtimev1.ListInstancesRequest
	(*ListInstancesResponse)(nil),  // 9: runtimev1.ListInstancesResponse
	(*InstanceStatus)(nil),         // 10: runtimev1.InstanceStatus
	(*NetworkConfig)(nil),          // 11: runtimev1.NetworkConfig
}
var file_packages_contracts_runtimev1_runtime_proto_depIdxs = []int32{
	11, // 0: runtimev1.CreateInstanceRequest.network:type_name -> runtimev1.NetworkConfig
	10, // 1: runtimev1.ListInstancesResponse.instances:type_name -> runtimev1.InstanceStatus
	0,  // 2: runtimev1.RuntimeService.CreateInstance:input_type -> runtimev1.CreateInstanceRequest
	2,  // 3: runtimev1.RuntimeService.StartInstance:input_type -> runtimev1.StartInstanceRequest
	4,  // 4: runtimev1.RuntimeService.StopInstance:input_type -> runtimev1.StopInstanceRequest
	6,  // 5: runtimev1.RuntimeService.DeleteInstance:input_type -> runtimev1.DeleteInstanceRequest
	8,  // 6: runtimev1.RuntimeService.ListInstances:input_type -> runtimev1.ListInstancesRequest
	1,  // 7: runtimev1.RuntimeService.CreateInstance:output_type -> runtimev1.CreateInstanceResponse
	3,  // 8: runtimev1.RuntimeService.StartInstance:output_type -> runtimev1.StartInstanceResponse
	5,  // 9: runtimev1.RuntimeService.StopInstance:output_type -> runtimev1.StopInstanceResponse
	7,  // 10: runtimev1.RuntimeService.DeleteInstance:output_type -> runtimev1.DeleteInstanceResponse
	9,  // 11: runtimev1.RuntimeService.ListInstances:output_type -> runtimev1.ListInstancesResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_packages_contracts_runtimev1_runtime_proto_init() }
func file_packages_contracts_runtimev1_runtime_proto_init() {
	if File_packages_contracts_runtimev1_runtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packages_contracts_runtimev1_runtime_proto_rawDesc), len(file_packages_contracts_runtimev1_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_packages_contracts_runtimev1_runtime_proto_goTypes,
		DependencyIndexes: file_packages_contracts_runtimev1_runtime_proto_depIdxs,
		MessageInfos:      file_packages_contracts_runtimev1_runtime_proto_msgTypes,
	}.Build()
	File_packages_contracts_runtimev1_runtime_proto = out.File
	file_packages_contracts_runtimev1_runtime_proto_goTypes = nil
	file_packages_contracts_runtimev1_runtime_proto_depIdxs = nil
}
